# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: f8587680235e78bf3d3abe6679f3adf9fc8abd7e10674efb780e9118e4826fd8200bcacbbc4e03e329fa9b1fa1685af74c1ed5ceaf4b9bf0a2a31708cbe8c929

test:
  secret_key_base: c9a76fc68d6a7af8dccb591d5e46773a2a9da4e4c6ffb870bf83eb646cef9c7256c8915de209de6396b96df1c77f7cb37be73676b06380f9178c04e00f7a747f

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
